# Generated by Django 5.2 on 2025-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doordash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doordash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('restaurant_id', models.IntegerField()),
                ('restaurant_name', models.TextField()),
                ('restaurant_name_lower', models.TextField()),
                ('breadcrumb', models.TextField()),
                ('street_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('star_rating', models.FloatField()),
                ('reviews_count', models.IntegerField()),
                ('price_range', models.TextField()),
                ('cuisine1', models.TextField()),
                ('opening_hours', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('display_address', models.TextField()),
                ('category', models.TextField()),
                ('item_name', models.TextField()),
                ('item_name_lower', models.TextField()),
                ('item_description', models.TextField()),
                ('item_image', models.TextField()),
                ('item_price', models.TextField()),
            ],
            options={
                'db_table': 'doordash',
            },
        ),
    ]
